language: node_js
node_js:
  - "16"

# Only build on pull requests or the main branch
branches:
  only:
    - /^feature-\S+$/ # Matches any branch starting with "feature-" followed by a description
    - develop # Build on the develop branch
    - release # Build on the release branch

# Conditional build triggers
if: |
  (type = push AND branch =~ /^feature-\S+$/) OR  # Trigger build on pushes to feature branches
  (type = pull_request AND branch = develop) OR   # Trigger build on pull requests to develop
  (type = push AND branch = develop) OR           # Trigger build on pushes to develop
  (type = push AND branch = release)              # Trigger build on pushes to release

# Define environments for both front-end and back-end
env:
  global:
    - FRONTEND_DIR=Client
    - BACKEND_DIR=Server

services:
  - mongodb # Add MongoDB service for the back-end

before_script:
  # Set up MongoDB connection environment variables, if needed
  - sleep 15 # Give MongoDB service time to start
  - mongo mydb --eval 'db.createCollection("test");' # Example to create a test DB

# Install dependencies for both front-end and back-end
install:
  - cd $FRONTEND_DIR
  - npm install
  - cd ../$BACKEND_DIR
  - npm install

# Build and test both front-end and back-end
script:
  - cd ../$FRONTEND_DIR
  - npm run build

  - cd ../$BACKEND_DIR

deploy:
  provider: script
  skip_cleanup: true
  script: >-
    echo $RENDER_DEPLOY curl -v -X POST $RENDER_DEPLOY \
     -H "Authorization: Bearer $RENDER_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"branch":"main"}'
  on:
    branch: main

cache:
  directories:
    - $HOME/.npm
