language: node_js
node_js:
  - "16"

# Only build on pull requests or the main branch
branches:
  only:
    - main
    - develop

# Build only on pull requests, not on every commit
# if: type = pull_request

# Define environments for both front-end and back-end
env:
  global:
    - FRONTEND_DIR=Client
    - BACKEND_DIR=Server

services:
  - mongodb # Add MongoDB service for the back-end

before_script:
  # Set up MongoDB connection environment variables, if needed
  - sleep 15 # Give MongoDB service time to start
  - mongo mydb --eval 'db.createCollection("test");' # Example to create a test DB

# Install dependencies for both front-end and back-end
install:
  - cd $FRONTEND_DIR
  - npm install
  - cd ../$BACKEND_DIR
  - npm install

# Build and test both front-end and back-end
script:
  - cd ../$FRONTEND_DIR
  - npm run build

  - cd ../$BACKEND_DIR

deploy:
  provider: script
  skip_cleanup: true
  script: >-
    curl -X POST $RENDER_DEPLOY \
     -H "Authorization: Bearer $RENDER_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"branch":"main"}' # specify your branch if different
  on:
    branch: main

cache:
  directories:
    - $HOME/.npm
